anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_stake_pool = "t1LVbNwJZT3pxFQHfY65jp6QbvcTvda6oPSbaeKbYEs"
cardinal_reward_distributor = "t2youarTBdTv9eRXoDaMGCywbYjAteNF3Fuzvn8fXNj"

[programs.devnet]
cardinal_stake_pool = "t1LVbNwJZT3pxFQHfY65jp6QbvcTvda6oPSbaeKbYEs"
cardinal_reward_distributor = "t2youarTBdTv9eRXoDaMGCywbYjAteNF3Fuzvn8fXNj"

[programs.testnet]
cardinal_stake_pool = "t1LVbNwJZT3pxFQHfY65jp6QbvcTvda6oPSbaeKbYEs"
cardinal_reward_distributor = "t2youarTBdTv9eRXoDaMGCywbYjAteNF3Fuzvn8fXNj"

[programs.localnet]
cardinal_stake_pool = "t1LVbNwJZT3pxFQHfY65jp6QbvcTvda6oPSbaeKbYEs"
cardinal_reward_distributor = "t2youarTBdTv9eRXoDaMGCywbYjAteNF3Fuzvn8fXNj"
